/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AuthenticationResponse type.
 */
public class AuthenticationResponse {
    private String issuedAt;
    private String applicationName;
    private String scope;
    private String status;
    private String expiresIn;
    private String tokenType;
    private String clientId;
    private String accessToken;

    /**
     * Default constructor.
     */
    public AuthenticationResponse() {
    }

    /**
     * Initialization constructor.
     * @param  issuedAt  String value for issuedAt.
     * @param  applicationName  String value for applicationName.
     * @param  scope  String value for scope.
     * @param  status  String value for status.
     * @param  expiresIn  String value for expiresIn.
     * @param  tokenType  String value for tokenType.
     * @param  clientId  String value for clientId.
     * @param  accessToken  String value for accessToken.
     */
    public AuthenticationResponse(
            String issuedAt,
            String applicationName,
            String scope,
            String status,
            String expiresIn,
            String tokenType,
            String clientId,
            String accessToken) {
        this.issuedAt = issuedAt;
        this.applicationName = applicationName;
        this.scope = scope;
        this.status = status;
        this.expiresIn = expiresIn;
        this.tokenType = tokenType;
        this.clientId = clientId;
        this.accessToken = accessToken;
    }

    /**
     * Getter for IssuedAt.
     * @return Returns the String
     */
    @JsonGetter("issued_at")
    public String getIssuedAt() {
        return issuedAt;
    }

    /**
     * Setter for IssuedAt.
     * @param issuedAt Value for String
     */
    @JsonSetter("issued_at")
    public void setIssuedAt(String issuedAt) {
        this.issuedAt = issuedAt;
    }

    /**
     * Getter for ApplicationName.
     * @return Returns the String
     */
    @JsonGetter("application_name")
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Setter for ApplicationName.
     * @param applicationName Value for String
     */
    @JsonSetter("application_name")
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    /**
     * Getter for Scope.
     * @return Returns the String
     */
    @JsonGetter("scope")
    public String getScope() {
        return scope;
    }

    /**
     * Setter for Scope.
     * @param scope Value for String
     */
    @JsonSetter("scope")
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for ExpiresIn.
     * @return Returns the String
     */
    @JsonGetter("expires_in")
    public String getExpiresIn() {
        return expiresIn;
    }

    /**
     * Setter for ExpiresIn.
     * @param expiresIn Value for String
     */
    @JsonSetter("expires_in")
    public void setExpiresIn(String expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * Getter for TokenType.
     * @return Returns the String
     */
    @JsonGetter("token_type")
    public String getTokenType() {
        return tokenType;
    }

    /**
     * Setter for TokenType.
     * @param tokenType Value for String
     */
    @JsonSetter("token_type")
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * Getter for ClientId.
     * @return Returns the String
     */
    @JsonGetter("client_id")
    public String getClientId() {
        return clientId;
    }

    /**
     * Setter for ClientId.
     * @param clientId Value for String
     */
    @JsonSetter("client_id")
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for AccessToken.
     * @return Returns the String
     */
    @JsonGetter("access_token")
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Setter for AccessToken.
     * @param accessToken Value for String
     */
    @JsonSetter("access_token")
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Converts this AuthenticationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthenticationResponse [" + "issuedAt=" + issuedAt + ", applicationName="
                + applicationName + ", scope=" + scope + ", status=" + status + ", expiresIn="
                + expiresIn + ", tokenType=" + tokenType + ", clientId=" + clientId
                + ", accessToken=" + accessToken + "]";
    }

    /**
     * Builds a new {@link AuthenticationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthenticationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(issuedAt, applicationName, scope, status, expiresIn,
                tokenType, clientId, accessToken);
        return builder;
    }

    /**
     * Class to build instances of {@link AuthenticationResponse}.
     */
    public static class Builder {
        private String issuedAt;
        private String applicationName;
        private String scope;
        private String status;
        private String expiresIn;
        private String tokenType;
        private String clientId;
        private String accessToken;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  issuedAt  String value for issuedAt.
         * @param  applicationName  String value for applicationName.
         * @param  scope  String value for scope.
         * @param  status  String value for status.
         * @param  expiresIn  String value for expiresIn.
         * @param  tokenType  String value for tokenType.
         * @param  clientId  String value for clientId.
         * @param  accessToken  String value for accessToken.
         */
        public Builder(String issuedAt, String applicationName, String scope, String status,
                String expiresIn, String tokenType, String clientId, String accessToken) {
            this.issuedAt = issuedAt;
            this.applicationName = applicationName;
            this.scope = scope;
            this.status = status;
            this.expiresIn = expiresIn;
            this.tokenType = tokenType;
            this.clientId = clientId;
            this.accessToken = accessToken;
        }

        /**
         * Setter for issuedAt.
         * @param  issuedAt  String value for issuedAt.
         * @return Builder
         */
        public Builder issuedAt(String issuedAt) {
            this.issuedAt = issuedAt;
            return this;
        }

        /**
         * Setter for applicationName.
         * @param  applicationName  String value for applicationName.
         * @return Builder
         */
        public Builder applicationName(String applicationName) {
            this.applicationName = applicationName;
            return this;
        }

        /**
         * Setter for scope.
         * @param  scope  String value for scope.
         * @return Builder
         */
        public Builder scope(String scope) {
            this.scope = scope;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for expiresIn.
         * @param  expiresIn  String value for expiresIn.
         * @return Builder
         */
        public Builder expiresIn(String expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * Setter for tokenType.
         * @param  tokenType  String value for tokenType.
         * @return Builder
         */
        public Builder tokenType(String tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        /**
         * Setter for clientId.
         * @param  clientId  String value for clientId.
         * @return Builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Setter for accessToken.
         * @param  accessToken  String value for accessToken.
         * @return Builder
         */
        public Builder accessToken(String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Builds a new {@link AuthenticationResponse} object using the set fields.
         * @return {@link AuthenticationResponse}
         */
        public AuthenticationResponse build() {
            return new AuthenticationResponse(issuedAt, applicationName, scope, status, expiresIn,
                    tokenType, clientId, accessToken);
        }
    }
}
