/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Bank type.
 */
public class Bank {
    private String payerId;
    private String bankId;
    private String payerIdType;

    /**
     * Default constructor.
     */
    public Bank() {
    }

    /**
     * Initialization constructor.
     * @param  payerId  String value for payerId.
     * @param  bankId  String value for bankId.
     * @param  payerIdType  String value for payerIdType.
     */
    public Bank(
            String payerId,
            String bankId,
            String payerIdType) {
        this.payerId = payerId;
        this.bankId = bankId;
        this.payerIdType = payerIdType;
    }

    /**
     * Getter for PayerId.
     * @return Returns the String
     */
    @JsonGetter("payerId")
    public String getPayerId() {
        return payerId;
    }

    /**
     * Setter for PayerId.
     * @param payerId Value for String
     */
    @JsonSetter("payerId")
    public void setPayerId(String payerId) {
        this.payerId = payerId;
    }

    /**
     * Getter for BankId.
     * @return Returns the String
     */
    @JsonGetter("bankId")
    public String getBankId() {
        return bankId;
    }

    /**
     * Setter for BankId.
     * @param bankId Value for String
     */
    @JsonSetter("bankId")
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    /**
     * Getter for PayerIdType.
     * @return Returns the String
     */
    @JsonGetter("payerIdType")
    public String getPayerIdType() {
        return payerIdType;
    }

    /**
     * Setter for PayerIdType.
     * @param payerIdType Value for String
     */
    @JsonSetter("payerIdType")
    public void setPayerIdType(String payerIdType) {
        this.payerIdType = payerIdType;
    }

    /**
     * Converts this Bank into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Bank [" + "payerId=" + payerId + ", bankId=" + bankId + ", payerIdType="
                + payerIdType + "]";
    }

    /**
     * Builds a new {@link Bank.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Bank.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(payerId, bankId, payerIdType);
        return builder;
    }

    /**
     * Class to build instances of {@link Bank}.
     */
    public static class Builder {
        private String payerId;
        private String bankId;
        private String payerIdType;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  payerId  String value for payerId.
         * @param  bankId  String value for bankId.
         * @param  payerIdType  String value for payerIdType.
         */
        public Builder(String payerId, String bankId, String payerIdType) {
            this.payerId = payerId;
            this.bankId = bankId;
            this.payerIdType = payerIdType;
        }

        /**
         * Setter for payerId.
         * @param  payerId  String value for payerId.
         * @return Builder
         */
        public Builder payerId(String payerId) {
            this.payerId = payerId;
            return this;
        }

        /**
         * Setter for bankId.
         * @param  bankId  String value for bankId.
         * @return Builder
         */
        public Builder bankId(String bankId) {
            this.bankId = bankId;
            return this;
        }

        /**
         * Setter for payerIdType.
         * @param  payerIdType  String value for payerIdType.
         * @return Builder
         */
        public Builder payerIdType(String payerIdType) {
            this.payerIdType = payerIdType;
            return this;
        }

        /**
         * Builds a new {@link Bank} object using the set fields.
         * @return {@link Bank}
         */
        public Bank build() {
            return new Bank(payerId, bankId, payerIdType);
        }
    }
}
