/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Link type.
 */
public class Link {
    private String href;
    private String rel;

    /**
     * Default constructor.
     */
    public Link() {
    }

    /**
     * Initialization constructor.
     * @param  href  String value for href.
     * @param  rel  String value for rel.
     */
    public Link(
            String href,
            String rel) {
        this.href = href;
        this.rel = rel;
    }

    /**
     * Getter for Href.
     * @return Returns the String
     */
    @JsonGetter("href")
    public String getHref() {
        return href;
    }

    /**
     * Setter for Href.
     * @param href Value for String
     */
    @JsonSetter("href")
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * Getter for Rel.
     * @return Returns the String
     */
    @JsonGetter("rel")
    public String getRel() {
        return rel;
    }

    /**
     * Setter for Rel.
     * @param rel Value for String
     */
    @JsonSetter("rel")
    public void setRel(String rel) {
        this.rel = rel;
    }

    /**
     * Converts this Link into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Link [" + "href=" + href + ", rel=" + rel + "]";
    }

    /**
     * Builds a new {@link Link.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Link.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(href, rel);
        return builder;
    }

    /**
     * Class to build instances of {@link Link}.
     */
    public static class Builder {
        private String href;
        private String rel;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  href  String value for href.
         * @param  rel  String value for rel.
         */
        public Builder(String href, String rel) {
            this.href = href;
            this.rel = rel;
        }

        /**
         * Setter for href.
         * @param  href  String value for href.
         * @return Builder
         */
        public Builder href(String href) {
            this.href = href;
            return this;
        }

        /**
         * Setter for rel.
         * @param  rel  String value for rel.
         * @return Builder
         */
        public Builder rel(String rel) {
            this.rel = rel;
            return this;
        }

        /**
         * Builds a new {@link Link} object using the set fields.
         * @return {@link Link}
         */
        public Link build() {
            return new Link(href, rel);
        }
    }
}
