/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Merchant2 type.
 */
public class Merchant2 {
    private String merchantIdCode;

    /**
     * Default constructor.
     */
    public Merchant2() {
    }

    /**
     * Initialization constructor.
     * @param  merchantIdCode  String value for merchantIdCode.
     */
    public Merchant2(
            String merchantIdCode) {
        this.merchantIdCode = merchantIdCode;
    }

    /**
     * Getter for MerchantIdCode.
     * @return Returns the String
     */
    @JsonGetter("merchantIdCode")
    public String getMerchantIdCode() {
        return merchantIdCode;
    }

    /**
     * Setter for MerchantIdCode.
     * @param merchantIdCode Value for String
     */
    @JsonSetter("merchantIdCode")
    public void setMerchantIdCode(String merchantIdCode) {
        this.merchantIdCode = merchantIdCode;
    }

    /**
     * Converts this Merchant2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Merchant2 [" + "merchantIdCode=" + merchantIdCode + "]";
    }

    /**
     * Builds a new {@link Merchant2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Merchant2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(merchantIdCode);
        return builder;
    }

    /**
     * Class to build instances of {@link Merchant2}.
     */
    public static class Builder {
        private String merchantIdCode;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  merchantIdCode  String value for merchantIdCode.
         */
        public Builder(String merchantIdCode) {
            this.merchantIdCode = merchantIdCode;
        }

        /**
         * Setter for merchantIdCode.
         * @param  merchantIdCode  String value for merchantIdCode.
         * @return Builder
         */
        public Builder merchantIdCode(String merchantIdCode) {
            this.merchantIdCode = merchantIdCode;
            return this;
        }

        /**
         * Builds a new {@link Merchant2} object using the set fields.
         * @return {@link Merchant2}
         */
        public Merchant2 build() {
            return new Merchant2(merchantIdCode);
        }
    }
}
