/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Merchant type.
 */
public class Merchant {
    private String merchantIdCode;
    private String merchantUrl;
    private String callbackUrl;

    /**
     * Default constructor.
     */
    public Merchant() {
    }

    /**
     * Initialization constructor.
     * @param  merchantIdCode  String value for merchantIdCode.
     * @param  merchantUrl  String value for merchantUrl.
     * @param  callbackUrl  String value for callbackUrl.
     */
    public Merchant(
            String merchantIdCode,
            String merchantUrl,
            String callbackUrl) {
        this.merchantIdCode = merchantIdCode;
        this.merchantUrl = merchantUrl;
        this.callbackUrl = callbackUrl;
    }

    /**
     * Getter for MerchantIdCode.
     * @return Returns the String
     */
    @JsonGetter("merchantIdCode")
    public String getMerchantIdCode() {
        return merchantIdCode;
    }

    /**
     * Setter for MerchantIdCode.
     * @param merchantIdCode Value for String
     */
    @JsonSetter("merchantIdCode")
    public void setMerchantIdCode(String merchantIdCode) {
        this.merchantIdCode = merchantIdCode;
    }

    /**
     * Getter for MerchantUrl.
     * @return Returns the String
     */
    @JsonGetter("merchantUrl")
    public String getMerchantUrl() {
        return merchantUrl;
    }

    /**
     * Setter for MerchantUrl.
     * @param merchantUrl Value for String
     */
    @JsonSetter("merchantUrl")
    public void setMerchantUrl(String merchantUrl) {
        this.merchantUrl = merchantUrl;
    }

    /**
     * Getter for CallbackUrl.
     * @return Returns the String
     */
    @JsonGetter("callbackUrl")
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * Setter for CallbackUrl.
     * @param callbackUrl Value for String
     */
    @JsonSetter("callbackUrl")
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * Converts this Merchant into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Merchant [" + "merchantIdCode=" + merchantIdCode + ", merchantUrl=" + merchantUrl
                + ", callbackUrl=" + callbackUrl + "]";
    }

    /**
     * Builds a new {@link Merchant.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Merchant.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(merchantIdCode, merchantUrl, callbackUrl);
        return builder;
    }

    /**
     * Class to build instances of {@link Merchant}.
     */
    public static class Builder {
        private String merchantIdCode;
        private String merchantUrl;
        private String callbackUrl;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  merchantIdCode  String value for merchantIdCode.
         * @param  merchantUrl  String value for merchantUrl.
         * @param  callbackUrl  String value for callbackUrl.
         */
        public Builder(String merchantIdCode, String merchantUrl, String callbackUrl) {
            this.merchantIdCode = merchantIdCode;
            this.merchantUrl = merchantUrl;
            this.callbackUrl = callbackUrl;
        }

        /**
         * Setter for merchantIdCode.
         * @param  merchantIdCode  String value for merchantIdCode.
         * @return Builder
         */
        public Builder merchantIdCode(String merchantIdCode) {
            this.merchantIdCode = merchantIdCode;
            return this;
        }

        /**
         * Setter for merchantUrl.
         * @param  merchantUrl  String value for merchantUrl.
         * @return Builder
         */
        public Builder merchantUrl(String merchantUrl) {
            this.merchantUrl = merchantUrl;
            return this;
        }

        /**
         * Setter for callbackUrl.
         * @param  callbackUrl  String value for callbackUrl.
         * @return Builder
         */
        public Builder callbackUrl(String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        /**
         * Builds a new {@link Merchant} object using the set fields.
         * @return {@link Merchant}
         */
        public Merchant build() {
            return new Merchant(merchantIdCode, merchantUrl, callbackUrl);
        }
    }
}
