/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Merchant1 type.
 */
public class Merchant1 {
    private String merchantIdCode;
    private String callbackUrl;

    /**
     * Default constructor.
     */
    public Merchant1() {
    }

    /**
     * Initialization constructor.
     * @param  merchantIdCode  String value for merchantIdCode.
     * @param  callbackUrl  String value for callbackUrl.
     */
    public Merchant1(
            String merchantIdCode,
            String callbackUrl) {
        this.merchantIdCode = merchantIdCode;
        this.callbackUrl = callbackUrl;
    }

    /**
     * Getter for MerchantIdCode.
     * @return Returns the String
     */
    @JsonGetter("merchantIdCode")
    public String getMerchantIdCode() {
        return merchantIdCode;
    }

    /**
     * Setter for MerchantIdCode.
     * @param merchantIdCode Value for String
     */
    @JsonSetter("merchantIdCode")
    public void setMerchantIdCode(String merchantIdCode) {
        this.merchantIdCode = merchantIdCode;
    }

    /**
     * Getter for CallbackUrl.
     * @return Returns the String
     */
    @JsonGetter("callbackUrl")
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * Setter for CallbackUrl.
     * @param callbackUrl Value for String
     */
    @JsonSetter("callbackUrl")
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * Converts this Merchant1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Merchant1 [" + "merchantIdCode=" + merchantIdCode + ", callbackUrl=" + callbackUrl
                + "]";
    }

    /**
     * Builds a new {@link Merchant1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Merchant1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(merchantIdCode, callbackUrl);
        return builder;
    }

    /**
     * Class to build instances of {@link Merchant1}.
     */
    public static class Builder {
        private String merchantIdCode;
        private String callbackUrl;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  merchantIdCode  String value for merchantIdCode.
         * @param  callbackUrl  String value for callbackUrl.
         */
        public Builder(String merchantIdCode, String callbackUrl) {
            this.merchantIdCode = merchantIdCode;
            this.callbackUrl = callbackUrl;
        }

        /**
         * Setter for merchantIdCode.
         * @param  merchantIdCode  String value for merchantIdCode.
         * @return Builder
         */
        public Builder merchantIdCode(String merchantIdCode) {
            this.merchantIdCode = merchantIdCode;
            return this;
        }

        /**
         * Setter for callbackUrl.
         * @param  callbackUrl  String value for callbackUrl.
         * @return Builder
         */
        public Builder callbackUrl(String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        /**
         * Builds a new {@link Merchant1} object using the set fields.
         * @return {@link Merchant1}
         */
        public Merchant1 build() {
            return new Merchant1(merchantIdCode, callbackUrl);
        }
    }
}
