/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RefundReqBody type.
 */
public class RefundReqBody {
    private Merchant2 merchant;
    private Transaction2 transaction;

    /**
     * Default constructor.
     */
    public RefundReqBody() {
    }

    /**
     * Initialization constructor.
     * @param  merchant  Merchant2 value for merchant.
     * @param  transaction  Transaction2 value for transaction.
     */
    public RefundReqBody(
            Merchant2 merchant,
            Transaction2 transaction) {
        this.merchant = merchant;
        this.transaction = transaction;
    }

    /**
     * Getter for Merchant.
     * @return Returns the Merchant2
     */
    @JsonGetter("merchant")
    public Merchant2 getMerchant() {
        return merchant;
    }

    /**
     * Setter for Merchant.
     * @param merchant Value for Merchant2
     */
    @JsonSetter("merchant")
    public void setMerchant(Merchant2 merchant) {
        this.merchant = merchant;
    }

    /**
     * Getter for Transaction.
     * @return Returns the Transaction2
     */
    @JsonGetter("transaction")
    public Transaction2 getTransaction() {
        return transaction;
    }

    /**
     * Setter for Transaction.
     * @param transaction Value for Transaction2
     */
    @JsonSetter("transaction")
    public void setTransaction(Transaction2 transaction) {
        this.transaction = transaction;
    }

    /**
     * Converts this RefundReqBody into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RefundReqBody [" + "merchant=" + merchant + ", transaction=" + transaction + "]";
    }

    /**
     * Builds a new {@link RefundReqBody.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RefundReqBody.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(merchant, transaction);
        return builder;
    }

    /**
     * Class to build instances of {@link RefundReqBody}.
     */
    public static class Builder {
        private Merchant2 merchant;
        private Transaction2 transaction;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  merchant  Merchant2 value for merchant.
         * @param  transaction  Transaction2 value for transaction.
         */
        public Builder(Merchant2 merchant, Transaction2 transaction) {
            this.merchant = merchant;
            this.transaction = transaction;
        }

        /**
         * Setter for merchant.
         * @param  merchant  Merchant2 value for merchant.
         * @return Builder
         */
        public Builder merchant(Merchant2 merchant) {
            this.merchant = merchant;
            return this;
        }

        /**
         * Setter for transaction.
         * @param  transaction  Transaction2 value for transaction.
         * @return Builder
         */
        public Builder transaction(Transaction2 transaction) {
            this.transaction = transaction;
            return this;
        }

        /**
         * Builds a new {@link RefundReqBody} object using the set fields.
         * @return {@link RefundReqBody}
         */
        public RefundReqBody build() {
            return new RefundReqBody(merchant, transaction);
        }
    }
}
