/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RegularPaymentReqBody type.
 */
public class RegularPaymentReqBody {
    private Bank bank;
    private Merchant merchant;
    private Transaction transaction;

    /**
     * Default constructor.
     */
    public RegularPaymentReqBody() {
    }

    /**
     * Initialization constructor.
     * @param  bank  Bank value for bank.
     * @param  merchant  Merchant value for merchant.
     * @param  transaction  Transaction value for transaction.
     */
    public RegularPaymentReqBody(
            Bank bank,
            Merchant merchant,
            Transaction transaction) {
        this.bank = bank;
        this.merchant = merchant;
        this.transaction = transaction;
    }

    /**
     * Getter for Bank.
     * @return Returns the Bank
     */
    @JsonGetter("bank")
    public Bank getBank() {
        return bank;
    }

    /**
     * Setter for Bank.
     * @param bank Value for Bank
     */
    @JsonSetter("bank")
    public void setBank(Bank bank) {
        this.bank = bank;
    }

    /**
     * Getter for Merchant.
     * @return Returns the Merchant
     */
    @JsonGetter("merchant")
    public Merchant getMerchant() {
        return merchant;
    }

    /**
     * Setter for Merchant.
     * @param merchant Value for Merchant
     */
    @JsonSetter("merchant")
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

    /**
     * Getter for Transaction.
     * @return Returns the Transaction
     */
    @JsonGetter("transaction")
    public Transaction getTransaction() {
        return transaction;
    }

    /**
     * Setter for Transaction.
     * @param transaction Value for Transaction
     */
    @JsonSetter("transaction")
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }

    /**
     * Converts this RegularPaymentReqBody into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegularPaymentReqBody [" + "bank=" + bank + ", merchant=" + merchant
                + ", transaction=" + transaction + "]";
    }

    /**
     * Builds a new {@link RegularPaymentReqBody.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegularPaymentReqBody.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(bank, merchant, transaction);
        return builder;
    }

    /**
     * Class to build instances of {@link RegularPaymentReqBody}.
     */
    public static class Builder {
        private Bank bank;
        private Merchant merchant;
        private Transaction transaction;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  bank  Bank value for bank.
         * @param  merchant  Merchant value for merchant.
         * @param  transaction  Transaction value for transaction.
         */
        public Builder(Bank bank, Merchant merchant, Transaction transaction) {
            this.bank = bank;
            this.merchant = merchant;
            this.transaction = transaction;
        }

        /**
         * Setter for bank.
         * @param  bank  Bank value for bank.
         * @return Builder
         */
        public Builder bank(Bank bank) {
            this.bank = bank;
            return this;
        }

        /**
         * Setter for merchant.
         * @param  merchant  Merchant value for merchant.
         * @return Builder
         */
        public Builder merchant(Merchant merchant) {
            this.merchant = merchant;
            return this;
        }

        /**
         * Setter for transaction.
         * @param  transaction  Transaction value for transaction.
         * @return Builder
         */
        public Builder transaction(Transaction transaction) {
            this.transaction = transaction;
            return this;
        }

        /**
         * Builds a new {@link RegularPaymentReqBody} object using the set fields.
         * @return {@link RegularPaymentReqBody}
         */
        public RegularPaymentReqBody build() {
            return new RegularPaymentReqBody(bank, merchant, transaction);
        }
    }
}
