/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for RegularPaymentResponse type.
 */
public class RegularPaymentResponse {
    private List<Link> links;
    private String id;
    private String status;
    private Bank bank;
    private Merchant1 merchant;
    private Transaction1 transaction;
    private String creationTime;
    private String modificationTime;

    /**
     * Default constructor.
     */
    public RegularPaymentResponse() {
    }

    /**
     * Initialization constructor.
     * @param  links  List of Link value for links.
     * @param  id  String value for id.
     * @param  status  String value for status.
     * @param  bank  Bank value for bank.
     * @param  merchant  Merchant1 value for merchant.
     * @param  transaction  Transaction1 value for transaction.
     * @param  creationTime  String value for creationTime.
     * @param  modificationTime  String value for modificationTime.
     */
    public RegularPaymentResponse(
            List<Link> links,
            String id,
            String status,
            Bank bank,
            Merchant1 merchant,
            Transaction1 transaction,
            String creationTime,
            String modificationTime) {
        this.links = links;
        this.id = id;
        this.status = status;
        this.bank = bank;
        this.merchant = merchant;
        this.transaction = transaction;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for Links.
     * @return Returns the List of Link
     */
    @JsonGetter("links")
    public List<Link> getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * @param links Value for List of Link
     */
    @JsonSetter("links")
    public void setLinks(List<Link> links) {
        this.links = links;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Bank.
     * @return Returns the Bank
     */
    @JsonGetter("bank")
    public Bank getBank() {
        return bank;
    }

    /**
     * Setter for Bank.
     * @param bank Value for Bank
     */
    @JsonSetter("bank")
    public void setBank(Bank bank) {
        this.bank = bank;
    }

    /**
     * Getter for Merchant.
     * @return Returns the Merchant1
     */
    @JsonGetter("merchant")
    public Merchant1 getMerchant() {
        return merchant;
    }

    /**
     * Setter for Merchant.
     * @param merchant Value for Merchant1
     */
    @JsonSetter("merchant")
    public void setMerchant(Merchant1 merchant) {
        this.merchant = merchant;
    }

    /**
     * Getter for Transaction.
     * @return Returns the Transaction1
     */
    @JsonGetter("transaction")
    public Transaction1 getTransaction() {
        return transaction;
    }

    /**
     * Setter for Transaction.
     * @param transaction Value for Transaction1
     */
    @JsonSetter("transaction")
    public void setTransaction(Transaction1 transaction) {
        this.transaction = transaction;
    }

    /**
     * Getter for CreationTime.
     * @return Returns the String
     */
    @JsonGetter("creationTime")
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Setter for CreationTime.
     * @param creationTime Value for String
     */
    @JsonSetter("creationTime")
    public void setCreationTime(String creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for ModificationTime.
     * @return Returns the String
     */
    @JsonGetter("modificationTime")
    public String getModificationTime() {
        return modificationTime;
    }

    /**
     * Setter for ModificationTime.
     * @param modificationTime Value for String
     */
    @JsonSetter("modificationTime")
    public void setModificationTime(String modificationTime) {
        this.modificationTime = modificationTime;
    }

    /**
     * Converts this RegularPaymentResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegularPaymentResponse [" + "links=" + links + ", id=" + id + ", status=" + status
                + ", bank=" + bank + ", merchant=" + merchant + ", transaction=" + transaction
                + ", creationTime=" + creationTime + ", modificationTime=" + modificationTime + "]";
    }

    /**
     * Builds a new {@link RegularPaymentResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegularPaymentResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(links, id, status, bank, merchant, transaction, creationTime,
                modificationTime);
        return builder;
    }

    /**
     * Class to build instances of {@link RegularPaymentResponse}.
     */
    public static class Builder {
        private List<Link> links;
        private String id;
        private String status;
        private Bank bank;
        private Merchant1 merchant;
        private Transaction1 transaction;
        private String creationTime;
        private String modificationTime;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  links  List of Link value for links.
         * @param  id  String value for id.
         * @param  status  String value for status.
         * @param  bank  Bank value for bank.
         * @param  merchant  Merchant1 value for merchant.
         * @param  transaction  Transaction1 value for transaction.
         * @param  creationTime  String value for creationTime.
         * @param  modificationTime  String value for modificationTime.
         */
        public Builder(List<Link> links, String id, String status, Bank bank, Merchant1 merchant,
                Transaction1 transaction, String creationTime, String modificationTime) {
            this.links = links;
            this.id = id;
            this.status = status;
            this.bank = bank;
            this.merchant = merchant;
            this.transaction = transaction;
            this.creationTime = creationTime;
            this.modificationTime = modificationTime;
        }

        /**
         * Setter for links.
         * @param  links  List of Link value for links.
         * @return Builder
         */
        public Builder links(List<Link> links) {
            this.links = links;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for bank.
         * @param  bank  Bank value for bank.
         * @return Builder
         */
        public Builder bank(Bank bank) {
            this.bank = bank;
            return this;
        }

        /**
         * Setter for merchant.
         * @param  merchant  Merchant1 value for merchant.
         * @return Builder
         */
        public Builder merchant(Merchant1 merchant) {
            this.merchant = merchant;
            return this;
        }

        /**
         * Setter for transaction.
         * @param  transaction  Transaction1 value for transaction.
         * @return Builder
         */
        public Builder transaction(Transaction1 transaction) {
            this.transaction = transaction;
            return this;
        }

        /**
         * Setter for creationTime.
         * @param  creationTime  String value for creationTime.
         * @return Builder
         */
        public Builder creationTime(String creationTime) {
            this.creationTime = creationTime;
            return this;
        }

        /**
         * Setter for modificationTime.
         * @param  modificationTime  String value for modificationTime.
         * @return Builder
         */
        public Builder modificationTime(String modificationTime) {
            this.modificationTime = modificationTime;
            return this;
        }

        /**
         * Builds a new {@link RegularPaymentResponse} object using the set fields.
         * @return {@link RegularPaymentResponse}
         */
        public RegularPaymentResponse build() {
            return new RegularPaymentResponse(links, id, status, bank, merchant, transaction,
                    creationTime, modificationTime);
        }
    }
}
