/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Transaction type.
 */
public class Transaction {
    private int amount;
    private String transactionType;
    private String currency;
    private String description;
    private String orderId;
    private String userAgent;
    private String userIpAddress;

    /**
     * Default constructor.
     */
    public Transaction() {
    }

    /**
     * Initialization constructor.
     * @param  amount  int value for amount.
     * @param  transactionType  String value for transactionType.
     * @param  currency  String value for currency.
     * @param  description  String value for description.
     * @param  orderId  String value for orderId.
     * @param  userAgent  String value for userAgent.
     * @param  userIpAddress  String value for userIpAddress.
     */
    public Transaction(
            int amount,
            String transactionType,
            String currency,
            String description,
            String orderId,
            String userAgent,
            String userIpAddress) {
        this.amount = amount;
        this.transactionType = transactionType;
        this.currency = currency;
        this.description = description;
        this.orderId = orderId;
        this.userAgent = userAgent;
        this.userIpAddress = userIpAddress;
    }

    /**
     * Getter for Amount.
     * @return Returns the int
     */
    @JsonGetter("amount")
    public int getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for int
     */
    @JsonSetter("amount")
    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     * Getter for TransactionType.
     * @return Returns the String
     */
    @JsonGetter("transactionType")
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Setter for TransactionType.
     * @param transactionType Value for String
     */
    @JsonSetter("transactionType")
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for OrderId.
     * @return Returns the String
     */
    @JsonGetter("orderId")
    public String getOrderId() {
        return orderId;
    }

    /**
     * Setter for OrderId.
     * @param orderId Value for String
     */
    @JsonSetter("orderId")
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for UserAgent.
     * @return Returns the String
     */
    @JsonGetter("userAgent")
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Setter for UserAgent.
     * @param userAgent Value for String
     */
    @JsonSetter("userAgent")
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * Getter for UserIpAddress.
     * @return Returns the String
     */
    @JsonGetter("userIpAddress")
    public String getUserIpAddress() {
        return userIpAddress;
    }

    /**
     * Setter for UserIpAddress.
     * @param userIpAddress Value for String
     */
    @JsonSetter("userIpAddress")
    public void setUserIpAddress(String userIpAddress) {
        this.userIpAddress = userIpAddress;
    }

    /**
     * Converts this Transaction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Transaction [" + "amount=" + amount + ", transactionType=" + transactionType
                + ", currency=" + currency + ", description=" + description + ", orderId=" + orderId
                + ", userAgent=" + userAgent + ", userIpAddress=" + userIpAddress + "]";
    }

    /**
     * Builds a new {@link Transaction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Transaction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(amount, transactionType, currency, description, orderId,
                userAgent, userIpAddress);
        return builder;
    }

    /**
     * Class to build instances of {@link Transaction}.
     */
    public static class Builder {
        private int amount;
        private String transactionType;
        private String currency;
        private String description;
        private String orderId;
        private String userAgent;
        private String userIpAddress;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  amount  int value for amount.
         * @param  transactionType  String value for transactionType.
         * @param  currency  String value for currency.
         * @param  description  String value for description.
         * @param  orderId  String value for orderId.
         * @param  userAgent  String value for userAgent.
         * @param  userIpAddress  String value for userIpAddress.
         */
        public Builder(int amount, String transactionType, String currency, String description,
                String orderId, String userAgent, String userIpAddress) {
            this.amount = amount;
            this.transactionType = transactionType;
            this.currency = currency;
            this.description = description;
            this.orderId = orderId;
            this.userAgent = userAgent;
            this.userIpAddress = userIpAddress;
        }

        /**
         * Setter for amount.
         * @param  amount  int value for amount.
         * @return Builder
         */
        public Builder amount(int amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for transactionType.
         * @param  transactionType  String value for transactionType.
         * @return Builder
         */
        public Builder transactionType(String transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for orderId.
         * @param  orderId  String value for orderId.
         * @return Builder
         */
        public Builder orderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

        /**
         * Setter for userAgent.
         * @param  userAgent  String value for userAgent.
         * @return Builder
         */
        public Builder userAgent(String userAgent) {
            this.userAgent = userAgent;
            return this;
        }

        /**
         * Setter for userIpAddress.
         * @param  userIpAddress  String value for userIpAddress.
         * @return Builder
         */
        public Builder userIpAddress(String userIpAddress) {
            this.userIpAddress = userIpAddress;
            return this;
        }

        /**
         * Builds a new {@link Transaction} object using the set fields.
         * @return {@link Transaction}
         */
        public Transaction build() {
            return new Transaction(amount, transactionType, currency, description, orderId,
                    userAgent, userIpAddress);
        }
    }
}
