/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Transaction2 type.
 */
public class Transaction2 {
    private int refundAmount;
    private String refundReason;
    private String refundId;
    private String originalPaymentId;
    private String userAgent;
    private String userIpAddress;

    /**
     * Default constructor.
     */
    public Transaction2() {
    }

    /**
     * Initialization constructor.
     * @param  refundAmount  int value for refundAmount.
     * @param  refundReason  String value for refundReason.
     * @param  refundId  String value for refundId.
     * @param  originalPaymentId  String value for originalPaymentId.
     * @param  userAgent  String value for userAgent.
     * @param  userIpAddress  String value for userIpAddress.
     */
    public Transaction2(
            int refundAmount,
            String refundReason,
            String refundId,
            String originalPaymentId,
            String userAgent,
            String userIpAddress) {
        this.refundAmount = refundAmount;
        this.refundReason = refundReason;
        this.refundId = refundId;
        this.originalPaymentId = originalPaymentId;
        this.userAgent = userAgent;
        this.userIpAddress = userIpAddress;
    }

    /**
     * Getter for RefundAmount.
     * @return Returns the int
     */
    @JsonGetter("refundAmount")
    public int getRefundAmount() {
        return refundAmount;
    }

    /**
     * Setter for RefundAmount.
     * @param refundAmount Value for int
     */
    @JsonSetter("refundAmount")
    public void setRefundAmount(int refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * Getter for RefundReason.
     * @return Returns the String
     */
    @JsonGetter("refundReason")
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * Setter for RefundReason.
     * @param refundReason Value for String
     */
    @JsonSetter("refundReason")
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }

    /**
     * Getter for RefundId.
     * @return Returns the String
     */
    @JsonGetter("refundId")
    public String getRefundId() {
        return refundId;
    }

    /**
     * Setter for RefundId.
     * @param refundId Value for String
     */
    @JsonSetter("refundId")
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * Getter for OriginalPaymentId.
     * @return Returns the String
     */
    @JsonGetter("originalPaymentId")
    public String getOriginalPaymentId() {
        return originalPaymentId;
    }

    /**
     * Setter for OriginalPaymentId.
     * @param originalPaymentId Value for String
     */
    @JsonSetter("originalPaymentId")
    public void setOriginalPaymentId(String originalPaymentId) {
        this.originalPaymentId = originalPaymentId;
    }

    /**
     * Getter for UserAgent.
     * @return Returns the String
     */
    @JsonGetter("userAgent")
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Setter for UserAgent.
     * @param userAgent Value for String
     */
    @JsonSetter("userAgent")
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * Getter for UserIpAddress.
     * @return Returns the String
     */
    @JsonGetter("userIpAddress")
    public String getUserIpAddress() {
        return userIpAddress;
    }

    /**
     * Setter for UserIpAddress.
     * @param userIpAddress Value for String
     */
    @JsonSetter("userIpAddress")
    public void setUserIpAddress(String userIpAddress) {
        this.userIpAddress = userIpAddress;
    }

    /**
     * Converts this Transaction2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Transaction2 [" + "refundAmount=" + refundAmount + ", refundReason=" + refundReason
                + ", refundId=" + refundId + ", originalPaymentId=" + originalPaymentId
                + ", userAgent=" + userAgent + ", userIpAddress=" + userIpAddress + "]";
    }

    /**
     * Builds a new {@link Transaction2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Transaction2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(refundAmount, refundReason, refundId, originalPaymentId,
                userAgent, userIpAddress);
        return builder;
    }

    /**
     * Class to build instances of {@link Transaction2}.
     */
    public static class Builder {
        private int refundAmount;
        private String refundReason;
        private String refundId;
        private String originalPaymentId;
        private String userAgent;
        private String userIpAddress;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  refundAmount  int value for refundAmount.
         * @param  refundReason  String value for refundReason.
         * @param  refundId  String value for refundId.
         * @param  originalPaymentId  String value for originalPaymentId.
         * @param  userAgent  String value for userAgent.
         * @param  userIpAddress  String value for userIpAddress.
         */
        public Builder(int refundAmount, String refundReason, String refundId,
                String originalPaymentId, String userAgent, String userIpAddress) {
            this.refundAmount = refundAmount;
            this.refundReason = refundReason;
            this.refundId = refundId;
            this.originalPaymentId = originalPaymentId;
            this.userAgent = userAgent;
            this.userIpAddress = userIpAddress;
        }

        /**
         * Setter for refundAmount.
         * @param  refundAmount  int value for refundAmount.
         * @return Builder
         */
        public Builder refundAmount(int refundAmount) {
            this.refundAmount = refundAmount;
            return this;
        }

        /**
         * Setter for refundReason.
         * @param  refundReason  String value for refundReason.
         * @return Builder
         */
        public Builder refundReason(String refundReason) {
            this.refundReason = refundReason;
            return this;
        }

        /**
         * Setter for refundId.
         * @param  refundId  String value for refundId.
         * @return Builder
         */
        public Builder refundId(String refundId) {
            this.refundId = refundId;
            return this;
        }

        /**
         * Setter for originalPaymentId.
         * @param  originalPaymentId  String value for originalPaymentId.
         * @return Builder
         */
        public Builder originalPaymentId(String originalPaymentId) {
            this.originalPaymentId = originalPaymentId;
            return this;
        }

        /**
         * Setter for userAgent.
         * @param  userAgent  String value for userAgent.
         * @return Builder
         */
        public Builder userAgent(String userAgent) {
            this.userAgent = userAgent;
            return this;
        }

        /**
         * Setter for userIpAddress.
         * @param  userIpAddress  String value for userIpAddress.
         * @return Builder
         */
        public Builder userIpAddress(String userIpAddress) {
            this.userIpAddress = userIpAddress;
            return this;
        }

        /**
         * Builds a new {@link Transaction2} object using the set fields.
         * @return {@link Transaction2}
         */
        public Transaction2 build() {
            return new Transaction2(refundAmount, refundReason, refundId, originalPaymentId,
                    userAgent, userIpAddress);
        }
    }
}
