/*
 * PayMarkEFTPOSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.paymark.apitest.controllers;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import nz.paymark.apitest.ApiHelper;
import nz.paymark.apitest.AuthManager;
import nz.paymark.apitest.Configuration;
import nz.paymark.apitest.exceptions.ApiException;
import nz.paymark.apitest.http.Headers;
import nz.paymark.apitest.http.client.HttpClient;
import nz.paymark.apitest.http.client.HttpContext;
import nz.paymark.apitest.http.request.HttpRequest;
import nz.paymark.apitest.http.response.HttpResponse;
import nz.paymark.apitest.http.response.HttpStringResponse;
import nz.paymark.apitest.models.AuthenticationResponse;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AuthController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public AuthController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }


    /**
     * @param  contentType  Required parameter: Example: application/x-www-form-urlencoded
     * @param  authorization  Required parameter: Example: Basic
     *         dUhucXY2a3pveTJZQWM5NTdHRGhhbm5LUzZUVmltRzM6QkVBTGZhTVFuSnRsWEc4aQ==
     * @param  grantType  Required parameter: Example: client_credentials
     * @return    Returns the AuthenticationResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public AuthenticationResponse createAuthenticate(
            final String contentType,
            final String authorization,
            final String grantType) throws ApiException, IOException {
        HttpRequest request = buildCreateAuthenticateRequest(contentType, authorization, grantType);
        authManagers.get("global").apply(request);

        HttpResponse response = getClientInstance().execute(request, false);
        HttpContext context = new HttpContext(request, response);

        return handleCreateAuthenticateResponse(context);
    }

    /**
     * @param  contentType  Required parameter: Example: application/x-www-form-urlencoded
     * @param  authorization  Required parameter: Example: Basic
     *         dUhucXY2a3pveTJZQWM5NTdHRGhhbm5LUzZUVmltRzM6QkVBTGZhTVFuSnRsWEc4aQ==
     * @param  grantType  Required parameter: Example: client_credentials
     * @return    Returns the AuthenticationResponse response from the API call
     */
    public CompletableFuture<AuthenticationResponse> createAuthenticateAsync(
            final String contentType,
            final String authorization,
            final String grantType) {
        return makeHttpCallAsync(() -> buildCreateAuthenticateRequest(contentType, authorization,
                grantType),
            req -> authManagers.get("global").applyAsync(req)
                .thenCompose(request -> getClientInstance()
                        .executeAsync(request, false)),
            context -> handleCreateAuthenticateResponse(context));
    }

    /**
     * Builds the HttpRequest object for createAuthenticate.
     */
    private HttpRequest buildCreateAuthenticateRequest(
            final String contentType,
            final String authorization,
            final String grantType) throws ApiException, IOException {
        //the base uri for api requests
        String baseUri = config.getBaseUri();

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/bearer/");

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("Content-Type", contentType);
        headers.add("Authorization", authorization);
        headers.add("user-agent", BaseController.userAgent);
        headers.add("accept", "application/json");

        //load all fields for the outgoing API request
        Map<String, Object> formParameters = new HashMap<>();
        formParameters.put("grant_type", grantType);

        //prepare and invoke the API call request to fetch the response
        HttpRequest request = getClientInstance().post(queryBuilder, headers, null,
                ApiHelper.prepareFormFields(formParameters));

        return request;
    }

    /**
     * Processes the response for createAuthenticate.
     * @return An object of type AuthenticationResponse
     */
    private AuthenticationResponse handleCreateAuthenticateResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        String responseBody = ((HttpStringResponse) response).getBody();
        AuthenticationResponse result = ApiHelper.deserialize(responseBody,
                AuthenticationResponse.class);

        return result;
    }

}